### PR TITLE
Fix bluespec-compiler for Ubuntu 24.04 to 26.04

### PR DESCRIPTION
**Pull request by tmarkettos**
This PR fixes the Haskell setup for building bluespec-compiler. It also corrects a dependency apt package name.

Tested on Ubuntu 24.04, 25.10 and 26.04.

### CODE REVIEW

File: pycheribuild/projects/bluespec_compiler.py [hunk 1]
```diff
@@ -64,7 +64,7 @@ def compile(self, **kwargs):
 
     def install(self, **kwargs):
         try:
-            self.run_cmd("cabal", "v1-update")
+            self.run_cmd("cabal", "update")
```
Comment (jrtc27) [inline pycheribuild/projects/bluespec_compiler.py:67]: Hm, so v1-update has been removed but v1-install remains? I'd naively assume they'd go together

Comment (tmarkettos) [reply pycheribuild/projects/bluespec_compiler.py:67]: It seems that way - 'update; v1-install' is what the upstream Bluespec repo recommends.

I tried v2-install but ran into problems as it needs to do `make GHC="ghc -package-env default"` and I couldn't get that to work (I don't know if cheribuild was failing to escape that correctly, but even when I did it by hand it didn't work).

Comment (jrtc27) [reply pycheribuild/projects/bluespec_compiler.py:67]: Interesting. I assume this is also fine on 22.04, but could you please check that, given it's still supported and we have a bunch of machines (e.g. technos) on it?

File: pycheribuild/projects/bluespec_compiler.py [hunk 2]
```diff
@@ -64,8 +64,9 @@ def compile(self, **kwargs):
 
     def install(self, **kwargs):
         try:
-            self.run_cmd("cabal", "v1-update")
-            self.run_cmd("cabal", "v1-install", "regex-compat", "syb", "old-time", "split", cwd=self.source_dir)
+            self.run_cmd("cabal", "update")
+            self.run_cmd("cabal", "v1-install", "regex-compat", "syb", "old-time", "split",
+                         "strict-concurrency", cwd=self.source_dir)
```
Comment (jrtc27) [inline pycheribuild/projects/bluespec_compiler.py]: ruff will want this as one argument per line with trailing comma, I think:
```suggestion
            self.run_cmd(
                "cabal",
                "v1-install",
                "regex-compat",
                "syb",
                "old-time",
                "split",
                "strict-concurrency",
                cwd=self.source_dir,
            )
```

File: pycheribuild/projects/bluespec_compiler.py (hunk 1 above)
Comment (tmarkettos) [reply pycheribuild/projects/bluespec_compiler.py:67]: Looks like the cabal install worked on 22.04, but it won't build with the supplied ghc-8.8.4:
```
[165 of 227] Compiling RSchedule        ( RSchedule.hs, /home/atm26/cheri/bsc/src/comp/../../build/comp/RSchedule.o )

RSchedule.hs:51:10: error:
    • Illegal instance declaration for ‘PPrint RAT’
        (All instance types must be of the form (T t1 ... tn)
         where T is not a synonym.
         Use TypeSynonymInstances if you want to disable this.)
    • In the instance declaration for ‘PPrint RAT’
   |
51 | instance PPrint RAT where
   |          ^^^^^^^^^^
```

Comment (tmarkettos) [reply pycheribuild/projects/bluespec_compiler.py:67]: Now reported as https://github.com/B-Lang-org/bsc/issues/963

Comment (jrtc27) [reply pycheribuild/projects/bluespec_compiler.py:67]: Thanks; given it got that far the cabal side of things here is probably fine. Can you please squash the formatting commits into the second one, then we can merge this?

**Review by arichardson — APPROVED** [review]
LGTM if it works for you

File: pycheribuild/projects/bluespec_compiler.py (hunk 1 above)
Comment (tmarkettos) [reply pycheribuild/projects/bluespec_compiler.py:67]: Done
